# NixOS Service Configuration for Unbound (Recursive DNS Resolver)
{ config, pkgs, lib, ... }:

{
  services.unbound = {
    enable = true;

    # Configure unbound.conf declaratively
    settings = {
      server = {
        # Listen on all interfaces on port 53
        interface = [ "0.0.0.0" "::" ];

        # Allow access from localhost and our private container subnet
        access-control = [
          "127.0.0.0/8 allow"
          "::1 allow"
          "10.10.10.0/24 allow"
          "10.20.20.0/24 allow"
          "fd00::/64 allow"
          "fd01::/64 allow"
        ];

        # DNS-over-TLS (DoT) on port 8853 — terminates TLS on Unbound itself.
        # Clients on the VPN or service LAN can use this as their DNS resolver
        # with encrypted transport. Uses the same wildcard cert generated by
        # nixnsd's ACME DNS-01 challenge. For external DoH access, nixnginx
        # proxies HTTPS to this port (or the resolver can use DoT directly).
        #
        # NOTE: TLS service is enabled automatically when tls-service-key and
        # tls-service-pem are set. The certs must be present at these paths
        # before unbound starts — sync them from nixnsd's ACME output.
        # (postRun in nixnsd/acme.nix copies certs to /var/lib/secrets/ssl/).
        #
        # If the cert files are missing on this container, unbound will fail
        # to start. Ensure they are synced from nixnsd before rebuilding.
        tls-port = 8853;
        tls-service-key = "/var/lib/secrets/ssl/minnecker.com/key.pem";
        tls-service-pem = "/var/lib/secrets/ssl/minnecker.com/fullchain.pem";

        # Use the system's root trust anchor store for DNSSEC validation.
        # Ensures Unbound can validate chains starting from the root.
        # auto-trust-anchor-file uses the NixOS module default.

        # Harden Unbound against specific vulnerabilities.
        harden-glue = "yes";
        harden-dnssec-stripped = "yes";
        harden-below-nxdomain = "yes";
        harden-referral-path = "yes";
        
        # Serve authoritative NSD zones locally via Unbound's auth-zone
        # feature so recursive queries for internal domains resolve
        # without forwarding to the NSD primary. This also provides DNSSEC
        # validation for those zones since we sign them in nixnsd.
        
        # Reduce max TTL to 1 hour so cached records don't stale for too long
        # but cache hits still help reduce upstream query volume.
        max-cache-ttl = 3600;
        cache-min-ttl = 60;
        
        # Neg cache for NXDOMAIN to prevent repeated queries for non-existent names.
        neg-cache-size = "16M";

        # Number of threads to spawn (match available CPU cores, default is
        # num-threads: auto-detected). Reduces latency under load.
        num-threads = 4;

        # Number of message slots for in-flight queries (reduces latency).
        msg-cache-size = "128M";

        # Request privacy: do not reveal the client's IP in PTR lookups.
        private-address = [
          "10.0.0.0/8"
          "172.16.0.0/12"
          "192.168.0.0/16"
          "fc00::/7"
          "fd00::/8"
          "::ffff:0:0/96"
        ];

        # Rate-limiting — suppress amplification attacks and limit the impact
        # of a single client hammering queries. Per-subnet: 500 responses/s,
        # per-client: 200 responses/s.
        ratelimit = 500;
        ratelimit-subnet-v4 = 24;
        ratelimit-subnet-v6 = 56;

        # Prefetch popular names to keep cache warm and reduce latency.
        prefetch = "yes";

        # Serve additional NS records alongside A/AAAA for better resolution.
        serve-expired = "yes";

        # DNSSEC validation enabled globally so all queries are validated.
        dnssec-enable = "yes";
        dnssec-validation = "auto";
      };

      # Forward local domain queries to the authoritative NSD nameserver
      stub-zone = [
        {
          name = "minnecker.com.";
          stub-addr = "10.20.20.11"; # nixnsd container IP
        }
        {
          name = "floffel.de.";
          stub-addr = "10.20.20.11";
        }
        {
          name = "sbminnecker.de.";
          stub-addr = "10.20.20.11";
        }
        {
          name = "substitution.art.";
          stub-addr = "10.20.20.11";
        }
      ];

      # Forward all other public queries to upstream resolvers (Cloudflare / Google)
      forward-zone = [
        {
          name = ".";
          forward-addr = [
            "1.1.1.1" # Cloudflare Primary
            "1.0.0.1" # Cloudflare Secondary
            "8.8.8.8" # Google Primary
          ];
        }
      ];
    };
  };
}
