{ config, pkgs, lib, ... }:

{
  systemd.tmpfiles.rules = [
    "d /var/vmail 0770 dovecot dovecot - -"
  ];

  # Generate Dovecot + Postfix LDAP config files from the shared mail
  # token (provisioned by nixidm's kanidm-mail-token service on every
  # Kanidm start).  Runs before dovecot and postfix so the files exist
  # at service startup.  The token file lives on the shared NAS mount
  # and is refreshed automatically; this service just renders the
  # per-consumer config files from it.
  systemd.services.mail-ldap-config = {
    description = "Generate Dovecot/Postfix LDAP config from shared mail token";
    # NOTE: the NixOS dovecot2 module names its unit "dovecot" (not
    # "dovecot2"), see nixos/modules/services/mail/dovecot.nix.
    wantedBy = [ "dovecot.service" "postfix.service" ];
    before = [ "dovecot.service" "postfix.service" ];
    # No RemainAfterExit: the service must re-enter "inactive (dead)" after
    # running so the mail-ldap-config.path watcher can re-trigger it when the
    # shared token file rotates. Boot ordering is unaffected — `before`/`wantedBy`
    # govern the start transaction, not steady-state.
    serviceConfig = {
      Type = "oneshot";
    };
    script = ''
      set -euo pipefail

      TOKEN_FILE=/var/lib/secrets/mail/ldap/ldap-token
      DEST=/var/lib/secrets/mail

      # Wait for the token file to exist (nixidm may not have run yet
      # on a fresh boot after a Kanidm DB restore)
      for i in $(seq 1 30); do
        if [ -s "$TOKEN_FILE" ]; then
          break
        fi
        echo "Waiting for mail LDAP token..."
        sleep 2
      done
      if [ ! -s "$TOKEN_FILE" ]; then
        echo "ERROR: $TOKEN_FILE not found — start nixidm first." >&2
        exit 1
      fi

      TOKEN=$(cat "$TOKEN_FILE")
      mkdir -p "$DEST/dovecot" "$DEST/postfix"

      # 1. Dovecot LDAP password file
      printf '%s' "$TOKEN" > "$DEST/dovecot/ldap-password.txt"
      chmod 644 "$DEST/dovecot/ldap-password.txt"
      if id dovecot >/dev/null 2>&1; then
        chown "$(id -u dovecot):$(id -g dovecot)" "$DEST/dovecot/ldap-password.txt"
      fi

      # 2. Postfix LDAP query configuration files
      write_cf() {
        local name="$1" filter="$2" attr="$3" format="$4"
        {
          echo "server_host = ldaps://ldap:636"
          echo "search_base = dc=minnecker,dc=com"
          echo "query_filter = $filter"
          echo "result_attribute = $attr"
          [ -n "$format" ] && [ "$format" != "-" ] && echo "result_format = $format"
          echo "bind = yes"
          echo "bind_dn = dn=token"
          echo "bind_pw = $TOKEN"
          echo "version = 3"
          echo "tls_require_cert = no"
        } > "$DEST/postfix/$name"
        chmod 644 "$DEST/postfix/$name"
      }

      write_cf ldap-recipients.cf  '(&(mail=%s)(memberof=cn=mail_users,ou=groups,dc=minnecker,dc=com))' mail -
      write_cf ldap-aliases.cf     '(&(mail=%s)(memberof=cn=mail_users,ou=groups,dc=minnecker,dc=com))' uid '%s@minnecker.com'
      write_cf ldap-senders.cf      '(&(mail=%s)(memberof=cn=mail_users,ou=groups,dc=minnecker,dc=com))' uid -
      write_cf ldap-catchalls.cf   '(&(mail=*@%d)(memberof=cn=mail_users,ou=groups,dc=minnecker,dc=com))' uid '%s@minnecker.com'
      write_cf ldap-domains.cf      '(mail=*@%s)' mail -

      if id postfix >/dev/null 2>&1; then
        chown -R "$(id -u postfix):$(id -g postfix)" "$DEST/postfix"
      fi

      echo "Dovecot/Postfix LDAP configs generated."
    '';
  };

  # The mail LDAP token is regenerated by nixidm's kanidm-mail-token service
  # on every Kanidm (re)start (so it is always signed by the current key
  # set, which is invalidated on a DB restore). The old token is destroyed
  # in the process, so any consumer still holding the previous token keeps
  # binding fine (the JWS signature stays valid and the token's own expiry
  # is None) but every search fails with "The token grace window has
  # passed ... SessionExpired" — the ApiTokenSession was removed from the
  # account entry.
  #
  # mail-ldap-config above only runs once at boot, so without a watcher
  # nixmail keeps presenting the destroyed token after every kanidm
  # restart. This path unit re-triggers the render + reloads the consumers
  # whenever the shared token file changes on the NAS mount, keeping the
  # baked-in bind credentials in sync.
  systemd.paths.mail-ldap-config = {
    description = "Watch the shared mail LDAP token for rotation";
    wantedBy = [ "multi-user.target" ];
    pathConfig = {
      PathChanged = "/var/lib/secrets/mail/ldap/ldap-token";
      Unit = "mail-ldap-config.service";
    };
  };

  # Re-rendering the .cf / password files is not enough — Postfix and
  # Dovecot read them once at startup and cache the bind credentials and
  # long-lived LDAP connections. Reload (not restart) so they re-read config
  # and drop/re-establish pooled LDAP connections with the fresh token,
  # without dropping active SMTP/IMAP sessions. Guarded with `is-active`
  # because this service also runs once at boot, before dovecot/postfix
  # have started, where a reload call would fail the oneshot.
  systemd.services.mail-ldap-config.serviceConfig.ExecStartPost = [
    "${pkgs.bash}/bin/bash -c 'systemctl is-active --quiet postfix && ${pkgs.postfix}/bin/postfix reload || true; systemctl is-active --quiet dovecot && ${pkgs.dovecot}/bin/doveadm reload || true'"
  ];

  systemd.services.dovecot.environment = {
    LDAPTLS_REQCERT = "never";
  };

  # Postfix Configuration
  services.postfix = {
    enable = true;

    # Use module settings for main.cf
    settings = {
      main = {
        myhostname = "backendmail.minnecker.com";
        mydomain = "minnecker.com";
        compatibility_level = "3.10";
        recipient_delimiter = "+.";
        smtpd_banner = "$myhostname ESMTP";

        local_destination_concurrency_limit = "10";
        default_destination_concurrency_limit = "20";
        inet_protocols = "all";

        # Deliver ALL mail via LMTP
        mailbox_transport = "lmtp:unix:private/dovecot-lmtp";
        virtual_transport = "lmtp:unix:private/dovecot-lmtp";

        smtpd_sasl_auth_enable = "yes";
        smtpd_sasl_local_domain = "minnecker.com";
        smtpd_sasl_type = "dovecot";
        smtpd_sasl_path = "private/auth";
        smtpd_sasl_security_options = "noanonymous";

        smtpd_recipient_restrictions = "permit_sasl_authenticated, permit_auth_destination, defer_unauth_destination, reject_rbl_client sbl-xbl.spamhaus.org, reject_rbl_client bl.spamcop.net, reject_unknown_recipient_domain, smtpd_reject_unlisted_recipient";
        smtpd_helo_restrictions = "permit_sasl_authenticated, reject_invalid_hostname, reject_unknown_hostname, reject_non_fqdn_hostname";
        smtpd_helo_required = "yes";
        biff = "no";

        virtual_alias_maps = "proxy:ldap:/var/lib/secrets/mail/postfix/ldap-aliases.cf, proxy:ldap:/var/lib/secrets/mail/postfix/ldap-catchalls.cf";
        virtual_mailbox_domains = "proxy:ldap:/var/lib/secrets/mail/postfix/ldap-domains.cf";
        virtual_mailbox_maps = "proxy:ldap:/var/lib/secrets/mail/postfix/ldap-recipients.cf";
        smtpd_sender_login_maps = "proxy:ldap:/var/lib/secrets/mail/postfix/ldap-senders.cf";
        local_recipient_maps = "$virtual_mailbox_maps";

        smtpd_milters = "inet:127.0.0.1:11332";
        non_smtpd_milters = "inet:127.0.0.1:11332";

        # A flaky/dead milter must NEVER tempfail delivery of otherwise
        # valid mail. If rspamd is slow or down, accept and deliver
        # without spam headers rather than bouncing the sender.
        milter_default_action = "accept";

        # Greylisting via postscreen (port 25 only; submission/submissions
        # bypass postscreen entirely, so authenticated mail is unaffected).
        # Intervals: 1h -> 2h -> 4h doubling grace for returning senders.
        postscreen_greylist_action = "enforce";
        postscreen_greylist_intervals = "1h:2h:4h";
        postscreen_dnsbl_sites = "zen.spamhaus.org=127.0.0.[2..11]*3,bl.spamcop.net=127.0.0.2*2";

        smtp_tls_security_level = "may";

        # TLS certificates for direct client connections (previously
        # terminated by the nginx mail proxy on ports 465/993/587/143).
        # The same cert/key pair used by nginx and Kanidm.
        smtpd_tls_cert_file = "/var/lib/secrets/ssl/minnecker.com/fullchain.pem";
        smtpd_tls_key_file = "/var/lib/secrets/ssl/minnecker.com/key.pem";
        smtpd_tls_security_level = "may";
      };

      master = {
        smtp = {
          type = "inet";
          private = false;
          chroot = false;
          maxproc = 1;
          command = "postscreen";
        };
        smtpd = {
          type = "unix";
          private = false;
          chroot = false;
          command = "smtpd";
        };
        submission = {
          type = "inet";
          private = false;
          chroot = false;
          command = "smtpd";
          args = [
            "-o" "smtpd_sasl_auth_enable=yes"
            "-o" "smtpd_sasl_type=dovecot"
            "-o" "smtpd_sasl_path=private/auth"
            "-o" "smtpd_sasl_security_options=noanonymous"
            "-o" "milter_macro_daemon_name=ORIGINATING"
          ];
        };
        # Implicit-TLS SMTPS (port 465). Previously terminated by the nginx
        # mail proxy; now exposed directly via host port forwarding. Wrapper
        # mode enables implicit TLS (no STARTTLS negotiation).
        submissions = {
          type = "inet";
          private = false;
          chroot = false;
          command = "smtpd";
          args = [
            "-o" "smtpd_tls_wrappermode=yes"
            "-o" "smtpd_sasl_auth_enable=yes"
            "-o" "smtpd_sasl_type=dovecot"
            "-o" "smtpd_sasl_path=private/auth"
            "-o" "smtpd_sasl_security_options=noanonymous"
            "-o" "milter_macro_daemon_name=ORIGINATING"
          ];
        };
      };
    };

    extraAliases = ''
      root: florian@minnecker.com
    '';
  };

  # Dovecot Configuration
  services.dovecot2 = {
    enable = true;

    settings = {
      dovecot_config_version = "2.4.4";
      dovecot_storage_version = "2.4.4";

      # TLS certificates for direct client connections (previously
      # terminated by the nginx mail proxy; now exposed directly via host
      # port forwarding).
      ssl_server_cert_file = "/var/lib/secrets/ssl/minnecker.com/fullchain.pem";
      ssl_server_key_file = "/var/lib/secrets/ssl/minnecker.com/key.pem";

      auth_allow_cleartext = true;
      # Verbose auth logging for debugging XOAUTH2 + userdb lookup failures.
      auth_verbose = true;
      auth_debug = true;
      # Advertise XOAUTH2 alongside PLAIN/LOGIN. The oauth2 passdb below
      # validates OAuth2 access tokens issued by Kanidm; PLAIN falls through
      # to the LDAP passdb (POSIX password) for legacy/webmail clients.
      auth_mechanisms = [ "plain" "login" "xoauth2" ];

      # The nginx mail proxy is removed — clients connect directly. Keep
      # PROXY protocol trust for any future HAProxy/TCP-proxy that may sit
      # in front, but it is no longer required for the auth flow.
      haproxy_trusted_networks = [ "10.20.20.14/32" "fd01::14/128" ];
      login_trusted_networks = [ "10.20.20.14/32" "fd01::14/128" ];

      lda_mailbox_autocreate = true;
      lda_mailbox_autosubscribe = true;

      mail_driver = "maildir";
      mail_uid = "dovecot";
      mail_gid = "dovecot";

      mail_home = "/var/vmail/%{user | domain | lower }/%{user}/";
      mail_path = "/var/vmail/%{user | domain | lower }/%{user | username | lower }/maildir/";

      protocols = [ "imap" "pop3" "lmtp" "sieve" ];
      recipient_delimiter = "+.";
      ssl = "yes";

      # Dovecot 2.4's lib-ldap sets LDAP_OPT_X_TLS_REQUIRE_CERT per-connection
      # based on ssl_client_require_valid_cert, overriding LDAPTLS_REQCERT.
      # Kanidm's TLS cert is for minnecker.com, not the short name 'ldap', so
      # disable cert verification for outbound LDAP connections (same as
      # Postfix's tls_require_cert=no).
      ssl_client_require_valid_cert = false;

      # OAuth2 token validation for XOAUTH2 authentication. Mail clients
      # (Thunderbird, K-9, Apple Mail, ...) that support OAuth2 obtain an
      # access token via Kanidm's browser-based authorisation code flow
      # (using the user's full Kanidm credentials, including MFA) and
      # present it to Dovecot via the XOAUTH2 SASL mechanism.
      #
      # Dovecot 2.4 changed the OAuth2 model: the XOAUTH2/OAUTHBEARER
      # mechanisms no longer use a passdb for token validation. Instead,
      # auth_sasl_oauth2_initialize() calls db_oauth2_init() against the
      # *global* auth event, reading the top-level `oauth2 { }` named
      # filter. If that filter is absent (or only nested inside a passdb),
      # introspection_mode stays empty and the auth process fatals with
      # "Cannot initialize oauth2: Missing oauth2_introspection_mode
      # setting" on startup — which surfaces as "Auth process broken" and
      # the master service throttling login attempts.
      #
      # Dovecot validates the token by calling Kanidm's OIDC userinfo
      # endpoint with the token as a Bearer header (introspection_mode =
      # auth). Kanidm returns the user's claims (sub, email, ...); Dovecot
      # extracts the `email` field as the IMAP/SMTP username and proceeds
      # with the userdb lookup below.
      #
      # This eliminates the need for a separate POSIX password for mail —
      # the user authenticates once via Kanidm SSO and the mail client
      # caches/refreshes the token automatically.
      oauth2 = {
        # Kanidm's per-client OIDC userinfo endpoint. The short name
        # `nixidm` resolves via hosts.nix (10.20.20.15). TLS cert
        # verification is disabled globally (ssl_client_require_valid_cert
        # = false) because the cert is for minnecker.com, not the short
        # hostname.
        introspection_url = "https://nixidm:8443/oauth2/openid/mail/userinfo";
        # Send the token as Authorization: Bearer (GET). Kanidm's userinfo
        # endpoint expects this — not ?access_token= (which is the default
        # tokeninfo_url mode) or POST body (RFC 7662 introspection).
        introspection_mode = "auth";
        # Extract the user's email from the userinfo response as the
        # Dovecot username. The `email` scope is granted via the scope
        # map on the `mail` OAuth2 client in kanidm.nix.
        username_attribute = "email";
      };

      # The XOAUTH2 mechanism reads the global `oauth2 { }` filter above.
      # This passdb exists only so that the post-token credential lookup
      # (auth_request_lookup_credentials, run after a successful XOAUTH2
      # token validation) hits a passdb that re-validates the token and
      # returns OK, instead of falling through to the LDAP passdb (which
      # would try to LDAP-bind with the OAuth2 token as a password and
      # fail). It inherits the introspection_* settings from the global
      # filter, so no nested `oauth2 { }` block is needed here.
      "passdb oauth2" = {
        driver = "oauth2";
      };

      "passdb ldap" = {
        driver = "ldap";
        ldap_uris = "ldaps://ldap";
        ldap_auth_dn = "dn=token";
        ldap_auth_dn_password = "</var/lib/secrets/mail/dovecot/ldap-password.txt";
        ldap_base = "dc=minnecker,dc=com";
        passdb_ldap_filter = "(&(|(mail=%{user})(uid=%{user}))(memberof=cn=mail_users,ou=groups,dc=minnecker,dc=com))";
        # Kanidm does NOT expose userPassword over LDAP. Password verification
        # must happen via an LDAP bind as the found user DN using their POSIX
        # password (kanidm person posix set-password). Without passdb_ldap_bind
        # Dovecot tries to read userPassword and auth always fails.
        passdb_ldap_bind = true;
      };

      "userdb ldap" = {
        driver = "ldap";
        ldap_uris = "ldaps://ldap";
        ldap_auth_dn = "dn=token";
        ldap_auth_dn_password = "</var/lib/secrets/mail/dovecot/ldap-password.txt";
        ldap_base = "dc=minnecker,dc=com";
        userdb_ldap_filter = "(&(|(mail=%{user})(uid=%{user}))(memberof=cn=mail_users,ou=groups,dc=minnecker,dc=com))";
      };

      "namespace inbox" = {
        inbox = true;
        separator = "/";
        subscriptions = true;
        type = "private";
        "mailbox Drafts" = { special_use = "\\Drafts"; };
        "mailbox Junk" = { special_use = "\\Junk"; };
        "mailbox Trash" = { special_use = "\\Trash"; };
        "mailbox Sent" = { special_use = "\\Sent"; };
        "mailbox \"Sent Messages\"" = { special_use = "\\Sent"; };
      };

      "service imap-login" = {
        "inet_listener imap" = { port = 143; };
        # Listener used by the nginx mail proxy (PROXY protocol). auth.js
        # points IMAP here (port 10143); haproxy is enabled so Dovecot reads
        # the real client IP from the PROXY header sent by nginx.
        "inet_listener imap_haproxy" = { port = 10143; haproxy = true; };
      };

      "service pop3-login" = { "inet_listener pop3" = { port = 110; }; };
      "service submission-login" = { "inet_listener submission" = { port = 587; }; };
      "service managesieve-login" = { "inet_listener sieve" = { port = 4190; }; };

      "service lmtp" = {
        "unix_listener /var/lib/postfix/queue/private/dovecot-lmtp" = {
          group = "postfix"; mode = "0666"; user = "postfix";
        };
      };

      "service auth" = {
        "unix_listener /var/lib/postfix/queue/private/auth" = {
          group = "postfix"; mode = "0666"; user = "postfix";
        };
      };

      "protocol lda" = { mail_plugins = "$mail_plugins sieve fts"; };
      "protocol lmtp" = { mail_plugins = "$mail_plugins sieve fts"; };
      # Full-text search on the IMAP side (flatcurve indexes on delivery via
      # lmtp; searching happens over imap).
      "protocol imap" = { mail_plugins = "$mail_plugins fts"; };

      # Sieve 2.4 settings. Enable the extensions our routing script and
      # user-facing vacation/notify scripts rely on.
      sieve_extensions = [ "envelope" "notify" "vacation" ];
      sieve_global_extensions = [ "envelope" "variables" "mailbox" ];

      # FTS (flatcurve, bundled). Tuning keys confirmed against dovecot 2.4;
      # adjust threads/token length after observing load in production.
      plugin = {
        fts = "flatcurve";
        fts_autoindex = "yes";
        fts_autoindex_exclude = "\\Junk";
        fts_flatcurve_min_token_len = "2";
        fts_flatcurve_max_threads = "2";
      };

      # Flatcurve indexing workers.
      "service indexer" = { process_limit = "1"; };
      "service indexer-worker" = { process_limit = "2"; };

      # Global BEFORE sieve: routing (quarantine, spam->Junk, reports,
      # +detail auto-folder). Order of rules matters (see routing.sieve).
      "sieve_script routing" = {
        type = "before";
        path = "/etc/dovecot/routing.sieve";
        sieve_script_bin_path = "/var/lib/dovecot/routing.svbin";
      };
      "sieve_script personal" = { active_path = "~/.dovecot.sieve"; driver = "file"; path = "~/sieve"; };
    };
  };

  # Local Redis for rspamd: scan history (WebUI graphs) + bayes/statistics.
  # Bound to loopback only; rspamd connects with no password.
  services.redis.servers.rspamd = {
    enable = true;
    bind = "127.0.0.1";
    port = 6379;
    save = [ ];
    openFirewall = false;
  };

  # Rspamd configuration using module locals
  services.rspamd = {
    enable = true;

    workers = {
      # S0: make the production milter real. Postfix sends smtpd_milters to
      # inet:127.0.0.1:11332, but the NixOS module only starts `normal` +
      # `controller` workers by default (unix socket / 11334). Without this
      # rspamd_proxy worker nothing listens on 11332 and every milter call
      # fails/times out — so X-Spam-* headers (and hence the spam sieve and
      # the quarantine flag) never appear in production. self_scan lets the
      # proxy worker reuse the local `normal` worker.
      rspamd_proxy = {
        bindSockets = lib.mkForce [ "127.0.0.1:11332" ];
        extraConfig = ''
          upstream "local" {
            default = yes;
            self_scan = yes;
          }
        '';
      };

      # Controller/WebUI reachable from the nginx proxy container
      # (10.20.20.14 / fd01::14) for rspamd.minnecker.com, in addition to
      # loopback. secure_ip + password are set in local.d/worker-controller.inc.
      controller = {
        bindSockets = lib.mkForce [ "[::]:11334" ];
      };
    };

    locals = {
      "dkim_signing.conf".text = ''
        selector = "minnecker";
        domain = "minnecker.com";
        path = "/var/lib/secrets/mail/dkim/minnecker.com.private";
      '';

      # ARC: sign with the same key under the `arc` selector so forwarded
      # mail keeps an independent auth chain.
      "arc.conf".text = ''
        enabled = true;
        selector = "arc";
        domain = "minnecker.com";
        path = "/var/lib/secrets/mail/dkim/minnecker.com.private";
        sign_authenticated = true;
        sign_local = true;
        allow_envfrom_empty = true;
      '';

      # Point rspamd at the local Redis for history + stats.
      "redis.conf".text = ''
        servers = "127.0.0.1:6379";
      '';
      "history_redis.conf".text = ''
        servers = "127.0.0.1:6379";
      '';

      # Score bands. add_header adds the X-Spam-* headers (drives the spam
      # sieve); reject is raised well above the quarantine band so the
      # quarantine tier (milter_headers below) catches borderline mail in a
      # mailbox instead of bouncing it. Tune after observing real scores.
      "actions.conf".text = ''
        add_header = 6;
        reject = 40;
      '';

      # Add the built-in spam header AND a custom quarantine flag header.
      # Messages scoring >= 12 (but below reject=40) get
      # X-Rspamd-Quarantine: yes, which the global routing sieve redirects to
      # the quarantine mailbox. Do NOT define a `quarantine` action here: it
      # maps to Postfix's hold queue, not a mailbox.
      "milter_headers.conf".text = ''
        use = ["spam-header" "quarantine-flag"];
        extended_spam_headers = true;
        custom {
          quarantine-flag {
            header = "X-Rspamd-Quarantine";
            value = "yes";
            score = 12;
            condition = "default";
          }
        }
      '';

      # Controller auth: secure_ip addresses bypass auth for reads; other
      # clients (e.g. the public internet via the LDAP-gated nginx vhost)
      # still pass the nginx LDAP check, and write operations need the
      # password anyway. Passwords are read at runtime from the rw secrets
      # mount via rspamd's $file$ directive (plaintext, provisioned by the
      # mail-rspamd-password oneshot).
      "worker-controller.inc".text = ''
        secure_ip = ["127.0.0.1" "10.20.20.14" "fd01::14"];
        password = "$file$/var/lib/secrets/mail/rspamd/controller-password";
        enable_password = "$file$/var/lib/secrets/mail/rspamd/controller-enable-password";
      '';

      # Allow $file$ to read the controller passwords from the rw secrets
      # mount (outside the read-only /etc/rspamd config directory).
      "options.inc".text = ''
        secure_config = false;
      '';
    };
  };

  # Provision the DKIM/ARC RSA key if it does not exist yet (2048-bit) and
  # emit a ready-to-paste DNS hint file. Idempotent; runs before rspamd so
  # the signing key exists at startup. The operator pastes the published
  # records from /var/lib/secrets/mail/dkim/minnecker.dns into the zone and
  # bumps the serial (see nixnsd).
  systemd.services.mail-dkim-key = {
    description = "Provision DKIM/ARC signing key + DNS hint for rspamd";
    wantedBy = [ "rspamd.service" ];
    before = [ "rspamd.service" ];
    serviceConfig.Type = "oneshot";
    path = [ pkgs.openssl pkgs.coreutils ];
    script = ''
      set -euo pipefail
      D=/var/lib/secrets/mail/dkim
      KEY="$D/minnecker.com.private"
      HINT="$D/minnecker.dns"
      install -d -m 0700 -o rspamd -g rspamd "$D"
      if [ ! -s "$KEY" ]; then
        echo "Generating new 2048-bit DKIM/ARC key..."
        openssl genrsa -out "$KEY" 2048 2>/dev/null
      fi
      # Ensure rspamd (which runs as the rspamd user) can read the key.
      chown rspamd:rspamd "$KEY"
      chmod 600 "$KEY"
      PUBKEY=$(openssl rsa -in "$KEY" -pubout -outform DER 2>/dev/null | base64 | tr -d '\n')
      cat > "$HINT" <<EOF
; DNS hint for minnecker.com (operator pastes into the zone, then bumps serial).
; minnecker._domainkey
minnecker._domainkey IN TXT ( "v=DKIM1; k=rsa; " "p=$PUBKEY" )
; arc._domainkey (ARC uses the same key)
arc._domainkey IN TXT ( "v=DKIM1; k=rsa; " "p=$PUBKEY" )
EOF
      chown rspamd:rspamd "$HINT"
      chmod 640 "$HINT"
    '';
  };

  # Generate rspamd controller passwords on first boot into the rw secrets
  # mount. rspamd accepts a PLAINTEXT controller `password` (it compares
  # directly; only when the value starts with a $2$ bcrypt hash does it run
  # verify), so we store the generated plaintext and let the controller read
  # it via $file$. The operator finds/overrides the password at
  # /var/lib/secrets/mail/rspamd/controller-password (.enable- variant for
  # write ops). rspamadm pw cannot be used non-interactively here, hence the
  # plaintext approach.
  systemd.services.mail-rspamd-password = {
    description = "Provision rspamd controller passwords";
    wantedBy = [ "rspamd.service" ];
    before = [ "rspamd.service" ];
    serviceConfig.Type = "oneshot";
    path = [ pkgs.openssl pkgs.coreutils ];
    script = ''
      set -euo pipefail
      D=/var/lib/secrets/mail/rspamd
      install -d -m 0750 -o rspamd -g rspamd "$D"
      for f in controller-password controller-enable-password; do
        if [ ! -s "$D/$f" ]; then
          openssl rand -hex 20 > "$D/$f"
        fi
        chown rspamd:rspamd "$D/$f"
        chmod 600 "$D/$f"
      done
    '';
  };


  environment.systemPackages = [ pkgs.dovecot_pigeonhole ];

  # Global BEFORE sieve. Runs for every delivered message, before the user's
  # personal script. Rule ORDER is critical:
  #   1. Mail expressly addressed to the quarantine mailbox -> Quarantine and
  #      STOP. This MUST come first: a re-submitted (redirected) quarantined
  #      message would otherwise hit rule 2 again and loop forever.
  #   2. rspamd's quarantine verdict header -> redirect to the quarantine
  #      mailbox (alias -> postmaster -> this script files it into Quarantine).
  #   3. rspamd spam verdict headers -> Junk (consolidated from the previous
  #      standalone spam-global script so ordering with quarantine is
  #      deterministic).
  #   4. DMARC/TLS-RPT aggregate reports (To/Cc reports@) -> hidden .Reports
  #      mailbox that parsedmarc watches.
  #   5. recipient-detail addressing (user+tag / user.tag) -> tags/<detail>.
  # Prevents path traversal in the generated folder name.
  environment.etc."dovecot/routing.sieve".text = ''
    require ["fileinto", "mailbox", "envelope", "variables"];

    # 1. Quarantine loop guard / landing pad.
    if envelope :localpart "to" "quarantine" {
      fileinto :create "Quarantine";
      stop;
    }

    # 2. rspamd quarantine verdict -> quarantine mailbox.
    if header :contains "X-Rspamd-Quarantine" "yes" {
      redirect "quarantine@minnecker.com";
      stop;
    }

    # 3. Spam verdict -> Junk.
    if anyof (
      header :contains "X-Spam-Flag" "YES",
      header :contains "X-Spam" "Yes"
    ) {
      fileinto :create "Junk";
      stop;
    }

    # 4. DMARC / TLS-RPT aggregate reports -> .Reports (parsedmarc watches it).
    if anyof (
      header :contains "To" "reports@minnecker.com",
      header :contains "Cc" "reports@minnecker.com"
    ) {
      fileinto :create ".Reports";
      stop;
    }

    # 5. Auto-folder routing by recipient detail (user+tag / user.tag).
    if envelope :detail :matches "to" "*" {
      if allof (
        not string :is "''${1}" "",
        not string :contains "''${1}" "/",
        not string :is "''${1}" ".",
        not string :is "''${1}" ".."
      ) {
        fileinto :create "tags/''${1}";
        stop;
      }
    }
  '';

  # Export Dovecot stats to Prometheus via the node_exporter textfile
  # collector (already enabled globally, directory 0755 node-exporter).
  # Runs every minute; writes dovecot.prom only on success (keeps the last
  # good file on transient failures).
  systemd.services.dovecot-stats-exporter = {
    description = "Export Dovecot stats to Prometheus textfile";
    serviceConfig.Type = "oneshot";
    path = [ pkgs.dovecot pkgs.coreutils ];
    script = ''
      set -euo pipefail
      OUT=/var/lib/node-exporter-textfile/dovecot.prom
      TMP=$(mktemp)
      # Prefer the native Prometheus format; fall back to parsing the
      # classic key=value dump.
      if ! doveadm stats dump --format prometheus > "$TMP" 2>/dev/null; then
        doveadm stats dump 2>/dev/null | awk '{gsub(/\./, "_"); printf "dovecot_%s %s\n", $1, $2}' > "$TMP" || { rm -f "$TMP"; exit 0; }
      fi
      if [ -s "$TMP" ]; then
        install -m 0644 -o node-exporter -g node-exporter "$TMP" "$OUT"
      fi
      rm -f "$TMP"
    '';
  };
  systemd.timers.dovecot-stats-exporter = {
    description = "Periodically export Dovecot stats";
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "*:0/1";
      Unit = "dovecot-stats-exporter.service";
    };
  };



  # Notes: Ensure DKIM private key remains outside the Nix store at
  # /var/lib/secrets/mail/dkim/minnecker.com.private and is readable by rspamd.

  # DMARC + TLS-RPT report processing (parsedmarc).
  #
  # parsedmarc reads DMARC/TLS-RPT aggregate mail from the postmaster
  # mailbox over IMAP (loopback, STARTTLS not required) and sends a daily
  # digest via our own submission. It watches the hidden ".Reports" mailbox
  # that the routing sieve files report mail into (NO Elasticsearch / Splunk /
  # Redis — the digest + archived raw reports suffice; provision.* stays off
  # because it conflicts with the LDAP virtual-mail flow).
  #
  # Runtime credentials are read from the rw secrets mount at start:
  #   /var/lib/secrets/mail/parsedmarc/imap-password  (postmaster POSIX pw)
  # which the operator provisions manually (echo -n '<pw>' > ...; chmod 600).
  # reports@minnecker.com -> postmaster is a Kanidm alias managed by the
  # operator, not a Postfix alias.
  services.parsedmarc = {
    enable = true;

    provision = {
      localMail.enable = false;
      elasticsearch = false;
      geoIp = false;
      grafana.datasource = false;
      grafana.dashboard = false;
    };

    settings = {
      general = {
        save_aggregate = false;
        save_forensic = false;
      };
      mailbox = {
        watch = true;
        delete = false;
      };
      imap = {
        host = "127.0.0.1";
        port = 143;
        ssl = false;
        user = "postmaster@minnecker.com";
        password = { _secret = "/var/lib/secrets/mail/parsedmarc/imap-password"; };
      };
      smtp = {
        host = "127.0.0.1";
        port = 587;
        ssl = false;
        user = "reports@minnecker.com";
        from = "reports@minnecker.com";
        to = [ "florian@minnecker.com" ];
        password = { _secret = "/var/lib/secrets/mail/parsedmarc/imap-password"; };
      };
    };
  };

  # parsedmarc reads reports from the dovecot Maildir; ensure our dovecot
  # (unit "dovecot.service", not the module-default 2.3 "dovecot2.service")
  # is up first.
  systemd.services.parsedmarc.after = [ "dovecot.service" ];
}
