{ config, pkgs, lib, ... }:

{
  systemd.tmpfiles.rules = [
    "d /var/vmail 0770 dovecot dovecot - -"
  ];

  # Generate Dovecot + Postfix LDAP config files from the shared mail
  # token (provisioned by nixidm's kanidm-mail-token service on every
  # Kanidm start).  Runs before dovecot and postfix so the files exist
  # at service startup.  The token file lives on the shared NAS mount
  # and is refreshed automatically; this service just renders the
  # per-consumer config files from it.
  systemd.services.mail-ldap-config = {
    description = "Generate Dovecot/Postfix LDAP config from shared mail token";
    wantedBy = [ "dovecot2.service" "postfix.service" ];
    before = [ "dovecot2.service" "postfix.service" ];
    # No RemainAfterExit: the service must re-enter "inactive (dead)" after
    # running so the mail-ldap-config.path watcher can re-trigger it when the
    # shared token file rotates. Boot ordering is unaffected — `before`/`wantedBy`
    # govern the start transaction, not steady-state.
    serviceConfig = {
      Type = "oneshot";
    };
    script = ''
      set -euo pipefail

      TOKEN_FILE=/var/lib/secrets/mail/ldap/ldap-token
      DEST=/var/lib/secrets/mail

      # Wait for the token file to exist (nixidm may not have run yet
      # on a fresh boot after a Kanidm DB restore)
      for i in $(seq 1 30); do
        if [ -s "$TOKEN_FILE" ]; then
          break
        fi
        echo "Waiting for mail LDAP token..."
        sleep 2
      done
      if [ ! -s "$TOKEN_FILE" ]; then
        echo "ERROR: $TOKEN_FILE not found — start nixidm first." >&2
        exit 1
      fi

      TOKEN=$(cat "$TOKEN_FILE")
      mkdir -p "$DEST/dovecot" "$DEST/postfix"

      # 1. Dovecot LDAP password file
      printf '%s' "$TOKEN" > "$DEST/dovecot/ldap-password.txt"
      chmod 600 "$DEST/dovecot/ldap-password.txt"
      if id dovecot >/dev/null 2>&1; then
        chown "$(id -u dovecot):$(id -g dovecot)" "$DEST/dovecot/ldap-password.txt"
      fi

      # 2. Postfix LDAP query configuration files
      write_cf() {
        local name="$1" filter="$2" attr="$3" format="$4"
        {
          echo "server_host = ldaps://ldap:636"
          echo "search_base = dc=minnecker,dc=com"
          echo "query_filter = $filter"
          echo "result_attribute = $attr"
          [ -n "$format" ] && [ "$format" != "-" ] && echo "result_format = $format"
          echo "bind = yes"
          echo "bind_dn = dn=token"
          echo "bind_pw = $TOKEN"
          echo "version = 3"
          echo "tls_require_cert = no"
        } > "$DEST/postfix/$name"
        chmod 600 "$DEST/postfix/$name"
      }

      write_cf ldap-recipients.cf  '(&(mail=%s)(memberof=cn=mail_users,ou=groups,dc=minnecker,dc=com))' mail -
      write_cf ldap-aliases.cf     '(&(mail=%s)(memberof=cn=mail_users,ou=groups,dc=minnecker,dc=com))' uid '%s@minnecker.com'
      write_cf ldap-senders.cf      '(&(mail=%s)(memberof=cn=mail_users,ou=groups,dc=minnecker,dc=com))' uid -
      write_cf ldap-catchalls.cf   '(&(mail=*@%d)(memberof=cn=mail_users,ou=groups,dc=minnecker,dc=com))' uid '%s@minnecker.com'
      write_cf ldap-domains.cf      '(mail=*@%s)' mail -

      if id postfix >/dev/null 2>&1; then
        chown -R "$(id -u postfix):$(id -g postfix)" "$DEST/postfix"
      fi

      echo "Dovecot/Postfix LDAP configs generated."
    '';
  };

  # The mail LDAP token is regenerated by nixidm's kanidm-mail-token service
  # on every Kanidm (re)start (so it is always signed by the current key
  # set, which is invalidated on a DB restore). The old token is destroyed
  # in the process, so any consumer still holding the previous token keeps
  # binding fine (the JWS signature stays valid and the token's own expiry
  # is None) but every search fails with "The token grace window has
  # passed ... SessionExpired" — the ApiTokenSession was removed from the
  # account entry.
  #
  # mail-ldap-config above only runs once at boot, so without a watcher
  # nixmail keeps presenting the destroyed token after every kanidm
  # restart. This path unit re-triggers the render + reloads the consumers
  # whenever the shared token file changes on the NAS mount, keeping the
  # baked-in bind credentials in sync.
  systemd.paths.mail-ldap-config = {
    description = "Watch the shared mail LDAP token for rotation";
    wantedBy = [ "multi-user.target" ];
    pathConfig = {
      PathChanged = "/var/lib/secrets/mail/ldap/ldap-token";
      Unit = "mail-ldap-config.service";
    };
  };

  # Re-rendering the .cf / password files is not enough — Postfix and
  # Dovecot read them once at startup and cache the bind credentials and
  # long-lived LDAP connections. Reload (not restart) so they re-read config
  # and drop/re-establish pooled LDAP connections with the fresh token,
  # without dropping active SMTP/IMAP sessions. Guarded with `is-active`
  # because this service also runs once at boot, before dovecot/postfix
  # have started, where a reload call would fail the oneshot.
  systemd.services.mail-ldap-config.serviceConfig.ExecStartPost = [
    "${pkgs.bash}/bin/bash -c 'systemctl is-active --quiet postfix && ${pkgs.postfix}/bin/postfix reload || true; systemctl is-active --quiet dovecot && ${pkgs.dovecot}/bin/doveadm reload || true'"
  ];

  systemd.services.dovecot.environment = {
    LDAPTLS_REQCERT = "never";
  };

  # Postfix Configuration
  services.postfix = {
    enable = true;

    # Use module settings for main.cf
    settings = {
      main = {
        myhostname = "backendmail.minnecker.com";
        mydomain = "minnecker.com";
        compatibility_level = "3.10";
        recipient_delimiter = "+.";
        smtpd_banner = "$myhostname ESMTP";

        local_destination_concurrency_limit = "10";
        default_destination_concurrency_limit = "20";
        inet_protocols = "all";

        # Deliver ALL mail via LMTP
        mailbox_transport = "lmtp:unix:private/dovecot-lmtp";
        virtual_transport = "lmtp:unix:private/dovecot-lmtp";

        smtpd_sasl_auth_enable = "yes";
        smtpd_sasl_local_domain = "minnecker.com";
        smtpd_sasl_type = "dovecot";
        smtpd_sasl_path = "private/auth";
        smtpd_sasl_security_options = "noanonymous";

        smtpd_recipient_restrictions = "permit_sasl_authenticated, permit_auth_destination, defer_unauth_destination, reject_rbl_client sbl-xbl.spamhaus.org, reject_rbl_client bl.spamcop.net, reject_unknown_recipient_domain, smtpd_reject_unlisted_recipient";
        smtpd_helo_restrictions = "permit_sasl_authenticated, reject_invalid_hostname, reject_unknown_hostname, reject_non_fqdn_hostname";
        smtpd_helo_required = "yes";
        biff = "no";

        virtual_alias_maps = "proxy:ldap:/var/lib/secrets/mail/postfix/ldap-aliases.cf, proxy:ldap:/var/lib/secrets/mail/postfix/ldap-catchalls.cf";
        virtual_mailbox_domains = "proxy:ldap:/var/lib/secrets/mail/postfix/ldap-domains.cf";
        virtual_mailbox_maps = "proxy:ldap:/var/lib/secrets/mail/postfix/ldap-recipients.cf";
        smtpd_sender_login_maps = "proxy:ldap:/var/lib/secrets/mail/postfix/ldap-senders.cf";
        local_recipient_maps = "$virtual_mailbox_maps";

        smtpd_milters = "inet:127.0.0.1:11332";
        non_smtpd_milters = "inet:127.0.0.1:11332";

        smtp_tls_security_level = "may";

        # TLS certificates for direct client connections (previously
        # terminated by the nginx mail proxy on ports 465/993/587/143).
        # The same cert/key pair used by nginx and Kanidm.
        smtpd_tls_cert_file = "/var/lib/secrets/ssl/minnecker.com/fullchain.pem";
        smtpd_tls_key_file = "/var/lib/secrets/ssl/minnecker.com/key.pem";
        smtpd_tls_security_level = "may";
      };

      master = {
        smtp = {
          type = "inet";
          private = false;
          chroot = false;
          maxproc = 1;
          command = "postscreen";
        };
        smtpd = {
          type = "unix";
          private = false;
          chroot = false;
          command = "smtpd";
        };
        submission = {
          type = "inet";
          private = false;
          chroot = false;
          command = "smtpd";
          args = [
            "-o" "smtpd_sasl_auth_enable=yes"
            "-o" "smtpd_sasl_type=dovecot"
            "-o" "smtpd_sasl_path=private/auth"
            "-o" "smtpd_sasl_security_options=noanonymous"
            "-o" "milter_macro_daemon_name=ORIGINATING"
          ];
        };
        # Implicit-TLS SMTPS (port 465). Previously terminated by the nginx
        # mail proxy; now exposed directly via host port forwarding. Wrapper
        # mode enables implicit TLS (no STARTTLS negotiation).
        submissions = {
          type = "inet";
          private = false;
          chroot = false;
          command = "smtpd";
          args = [
            "-o" "smtpd_tls_wrappermode=yes"
            "-o" "smtpd_sasl_auth_enable=yes"
            "-o" "smtpd_sasl_type=dovecot"
            "-o" "smtpd_sasl_path=private/auth"
            "-o" "smtpd_sasl_security_options=noanonymous"
            "-o" "milter_macro_daemon_name=ORIGINATING"
          ];
        };
      };
    };

    extraAliases = ''
      root: florian@minnecker.com
    '';
  };

  # Dovecot Configuration
  services.dovecot2 = {
    enable = true;

    settings = {
      dovecot_config_version = "2.4.4";
      dovecot_storage_version = "2.4.4";

      # TLS certificates for direct client connections (previously
      # terminated by the nginx mail proxy; now exposed directly via host
      # port forwarding).
      ssl_server_cert_file = "/var/lib/secrets/ssl/minnecker.com/fullchain.pem";
      ssl_server_key_file = "/var/lib/secrets/ssl/minnecker.com/key.pem";

      auth_allow_cleartext = true;
      # Verbose auth logging for debugging XOAUTH2 + userdb lookup failures.
      auth_verbose = true;
      auth_debug = true;
      # Advertise XOAUTH2 alongside PLAIN/LOGIN. The oauth2 passdb below
      # validates OAuth2 access tokens issued by Kanidm; PLAIN falls through
      # to the LDAP passdb (POSIX password) for legacy/webmail clients.
      auth_mechanisms = [ "plain" "login" "xoauth2" ];

      # The nginx mail proxy is removed — clients connect directly. Keep
      # PROXY protocol trust for any future HAProxy/TCP-proxy that may sit
      # in front, but it is no longer required for the auth flow.
      haproxy_trusted_networks = [ "10.20.20.14/32" "fd01::14/128" ];
      login_trusted_networks = [ "10.20.20.14/32" "fd01::14/128" ];

      lda_mailbox_autocreate = true;
      lda_mailbox_autosubscribe = true;

      mail_driver = "maildir";
      mail_uid = "dovecot";
      mail_gid = "dovecot";

      mail_home = "/var/vmail/%{user | domain | lower }/%{user}/";
      mail_path = "/var/vmail/%{user | domain | lower }/%{user | username | lower }/maildir/";

      protocols = [ "imap" "pop3" "lmtp" "sieve" ];
      recipient_delimiter = "+.";
      ssl = "yes";

      # Dovecot 2.4's lib-ldap sets LDAP_OPT_X_TLS_REQUIRE_CERT per-connection
      # based on ssl_client_require_valid_cert, overriding LDAPTLS_REQCERT.
      # Kanidm's TLS cert is for minnecker.com, not the short name 'ldap', so
      # disable cert verification for outbound LDAP connections (same as
      # Postfix's tls_require_cert=no).
      ssl_client_require_valid_cert = false;

      # OAuth2 token validation for XOAUTH2 authentication. Mail clients
      # (Thunderbird, K-9, Apple Mail, ...) that support OAuth2 obtain an
      # access token via Kanidm's browser-based authorisation code flow
      # (using the user's full Kanidm credentials, including MFA) and
      # present it to Dovecot via the XOAUTH2 SASL mechanism.
      #
      # Dovecot 2.4 changed the OAuth2 model: the XOAUTH2/OAUTHBEARER
      # mechanisms no longer use a passdb for token validation. Instead,
      # auth_sasl_oauth2_initialize() calls db_oauth2_init() against the
      # *global* auth event, reading the top-level `oauth2 { }` named
      # filter. If that filter is absent (or only nested inside a passdb),
      # introspection_mode stays empty and the auth process fatals with
      # "Cannot initialize oauth2: Missing oauth2_introspection_mode
      # setting" on startup — which surfaces as "Auth process broken" and
      # the master service throttling login attempts.
      #
      # Dovecot validates the token by calling Kanidm's OIDC userinfo
      # endpoint with the token as a Bearer header (introspection_mode =
      # auth). Kanidm returns the user's claims (sub, email, ...); Dovecot
      # extracts the `email` field as the IMAP/SMTP username and proceeds
      # with the userdb lookup below.
      #
      # This eliminates the need for a separate POSIX password for mail —
      # the user authenticates once via Kanidm SSO and the mail client
      # caches/refreshes the token automatically.
      oauth2 = {
        # Kanidm's per-client OIDC userinfo endpoint. The short name
        # `nixidm` resolves via hosts.nix (10.20.20.15). TLS cert
        # verification is disabled globally (ssl_client_require_valid_cert
        # = false) because the cert is for minnecker.com, not the short
        # hostname.
        introspection_url = "https://nixidm:8443/oauth2/openid/mail/userinfo";
        # Send the token as Authorization: Bearer (GET). Kanidm's userinfo
        # endpoint expects this — not ?access_token= (which is the default
        # tokeninfo_url mode) or POST body (RFC 7662 introspection).
        introspection_mode = "auth";
        # Extract the user's email from the userinfo response as the
        # Dovecot username. The `email` scope is granted via the scope
        # map on the `mail` OAuth2 client in kanidm.nix.
        username_attribute = "email";
      };

      # The XOAUTH2 mechanism reads the global `oauth2 { }` filter above.
      # This passdb exists only so that the post-token credential lookup
      # (auth_request_lookup_credentials, run after a successful XOAUTH2
      # token validation) hits a passdb that re-validates the token and
      # returns OK, instead of falling through to the LDAP passdb (which
      # would try to LDAP-bind with the OAuth2 token as a password and
      # fail). It inherits the introspection_* settings from the global
      # filter, so no nested `oauth2 { }` block is needed here.
      "passdb oauth2" = {
        driver = "oauth2";
      };

      "passdb ldap" = {
        driver = "ldap";
        ldap_uris = "ldaps://ldap";
        ldap_auth_dn = "dn=token";
        ldap_auth_dn_password = "</var/lib/secrets/mail/dovecot/ldap-password.txt";
        ldap_base = "dc=minnecker,dc=com";
        passdb_ldap_filter = "(&(|(mail=%{user})(uid=%{user}))(memberof=cn=mail_users,ou=groups,dc=minnecker,dc=com))";
        # Kanidm does NOT expose userPassword over LDAP. Password verification
        # must happen via an LDAP bind as the found user DN using their POSIX
        # password (kanidm person posix set-password). Without passdb_ldap_bind
        # Dovecot tries to read userPassword and auth always fails.
        passdb_ldap_bind = true;
      };

      "userdb ldap" = {
        driver = "ldap";
        ldap_uris = "ldaps://ldap";
        ldap_auth_dn = "dn=token";
        ldap_auth_dn_password = "</var/lib/secrets/mail/dovecot/ldap-password.txt";
        ldap_base = "dc=minnecker,dc=com";
        userdb_ldap_filter = "(&(|(mail=%{user})(uid=%{user}))(memberof=cn=mail_users,ou=groups,dc=minnecker,dc=com))";
      };

      "namespace inbox" = {
        inbox = true;
        separator = "/";
        subscriptions = true;
        type = "private";
        "mailbox Drafts" = { special_use = "\\Drafts"; };
        "mailbox Junk" = { special_use = "\\Junk"; };
        "mailbox Trash" = { special_use = "\\Trash"; };
        "mailbox Sent" = { special_use = "\\Sent"; };
        "mailbox \"Sent Messages\"" = { special_use = "\\Sent"; };
      };

      "service imap-login" = {
        "inet_listener imap" = { port = 143; };
        # Listener used by the nginx mail proxy (PROXY protocol). auth.js
        # points IMAP here (port 10143); haproxy is enabled so Dovecot reads
        # the real client IP from the PROXY header sent by nginx.
        "inet_listener imap_haproxy" = { port = 10143; haproxy = true; };
      };

      "service pop3-login" = { "inet_listener pop3" = { port = 110; }; };
      "service submission-login" = { "inet_listener submission" = { port = 587; }; };
      "service managesieve-login" = { "inet_listener sieve" = { port = 4190; }; };

      "service lmtp" = {
        "unix_listener /var/lib/postfix/queue/private/dovecot-lmtp" = {
          group = "postfix"; mode = "0666"; user = "postfix";
        };
      };

      "service auth" = {
        "unix_listener /var/lib/postfix/queue/private/auth" = {
          group = "postfix"; mode = "0666"; user = "postfix";
        };
      };

      "protocol lda" = { mail_plugins = "$mail_plugins sieve"; };
      "protocol lmtp" = { mail_plugins = "$mail_plugins sieve"; };
      "sieve_script spam-global" = {
        type = "before";
        path = "/etc/dovecot/global-spam.sieve";
        sieve_script_bin_path = "/var/lib/dovecot/global-spam.svbin";
      };
      "sieve_script personal" = { active_path = "~/.dovecot.sieve"; driver = "file"; path = "~/sieve"; };
    };
  };

  # Rspamd configuration using module locals
  services.rspamd = {
    enable = true;
    locals."dkim_signing.conf".text = ''
      selector = "minnecker";
      domain = "minnecker.com";
      path = "/var/lib/secrets/mail/dkim/minnecker.com.private";
    '';
  };


  environment.systemPackages = [ pkgs.dovecot_pigeonhole ];

  # Global Sieve script to automatically move spam to the Junk folder
  environment.etc."dovecot/global-spam.sieve".text = ''
    require ["fileinto", "mailbox"];
    if anyof (
      header :contains "X-Spam-Flag" "YES",
      header :contains "X-Spam" "Yes"
    ) {
      fileinto :create "Junk";
      stop;
    }
  '';



  # Notes: Ensure DKIM private key remains outside the Nix store at
  # /var/lib/secrets/mail/dkim/minnecker.com.private and is readable by rspamd.
}
