# NixOS Service Configuration for the Nginx Reverse Proxy and Roundcube Webmail
{ config, pkgs, lib, ... }:

let
  nginx-auth-ldap = pkgs.stdenv.mkDerivation rec {
    pname = "nginx-auth-ldap";
    version = "241200eac8e4acae74d353291bd27f79e5ca3dc4";
    src = pkgs.fetchFromGitHub {
      owner = "kvspb";
      repo = "nginx-auth-ldap";
      rev = version;
      sha256 = "sha256-NE539zZ/OqSEZidgdPlv8rDJ6yvPyi+k4Hm5NNLpAPs=";
    };
    meta = {
      license = [ pkgs.lib.licenses.bsd2 ];
    };
  };
in
{
  # 1. Custom Nginx Service Configuration
  services.nginx = {
    enable = true;
    
    # Compile Nginx with mail proxy capabilities and custom modules
    package = (pkgs.nginx.override {
      withMail = true;
      withMailSsl = true;
      modules = [
        pkgs.nginxModules.brotli
        pkgs.nginxModules.njs
        nginx-auth-ldap
      ];
    }).overrideAttrs (oldAttrs: {
      buildInputs = oldAttrs.buildInputs ++ [ pkgs.openldap ];
    });

    # Set system-wide client max body size to allow large files in cloud/webmail
    clientMaxBodySize = "20G";

    # The kie.minnecker.com token map uses a "Bearer <token>" key (~71 chars)
    # which exceeds nginx's default 64-byte map hash bucket, so bump it.
    mapHashBucketSize = 128;

    # Common HTTP configurations loaded into Nginx http context.
    # The ldap.conf is generated by nixidm's kanidm-mail-token service and
    # shared via the read-only mail/ldap secrets mount (isolated subdir of
    # the mail secrets, so nixnginx never sees DKIM/Dovecot/Postfix secrets).
    commonHttpConfig = ''
      server_names_hash_bucket_size 128;
      proxy_headers_hash_max_size 1024;
      proxy_headers_hash_bucket_size 128;

      brotli on;
      auth_ldap_cache_enabled on;
      auth_ldap_cache_expiration_time 10000;
      auth_ldap_cache_size 1000;

      # Send access + error logs to syslog (journald) so Grafana Alloy's
      # journald source picks them up and ships them to Loki. Without this,
      # nginx logs only to /var/log/nginx/*.log and the monitoring dashboard's
      # {systemd_unit="nginx.service"} Loki queries return nothing.
      access_log syslog:server=unix:/dev/log;
      error_log syslog:server=unix:/dev/log;

      # Include LDAP configurations from the isolated mail/ldap secrets mount
      include /var/lib/secrets/mail/ldap/nginx-ldap.conf;

      # Include the bearer-token map for kie.minnecker.com (generated at
      # runtime by the kie-proxy-token oneshot from /var/lib/kie-proxy/token).
      include /var/lib/kie-proxy/nginx-map.conf;
    '';

    # 2. Upstream Definitions
    # Replicates the upstreams.conf from the Arch system
    upstreams = {
      forgejo.servers = { "nixforgejo:3000" = {}; };
      matrix.servers = { "nixmatrix:8008" = {}; };
      jitsy.servers = { "nixjitsi:80" = {}; };
      wikijs.servers = { "nixwikijs:3000" = {}; };
      vaultwarden.servers = { "nixvaultwarden:8080" = {}; };
      ki.servers = { "192.168.1.196:8080" = {}; };
      # OpenAI-compatible LLM endpoint on the same host as `ki` but on the
      # LLM API port (matches Open WebUI's OPENAI_API_BASE_URL). Gated by the
      # kie.minnecker.com vhost's bearer-token check (see kie-auth.js).
      kiellm.servers = { "192.168.1.196:52415" = {}; };
      openwebui.servers = { "nixopenwebui:8080" = {}; };
      nixmonitoring.servers = { "nixmonitoring:3000" = {}; };
      idm.servers = { "nixidm:8443" = {}; };
    };

    # 3. Virtual Hosts Configuration
    virtualHosts = {
      # Default catch-all site
      "default" = {
        default = true;
        listen = [
          { addr = "0.0.0.0"; port = 80; }
          { addr = "[::]"; port = 80; }
        ];
        serverName = "riese.minnecker.com _";
        root = "/usr/share/webapps/localhost/htdocs";
        extraConfig = ''
          error_page 500 502 503 504 /50x.html;
        '';
        locations."= /50x.html" = {
          root = "${pkgs.nginx}/html";
        };
      };

      # app.substitution.art
      "app.substitution.art" = {
        forceSSL = true;
        sslCertificate = "/var/lib/secrets/ssl/substitution.art/fullchain.pem";
        sslCertificateKey = "/var/lib/secrets/ssl/substitution.art/key.pem";
        root = "/usr/share/webapps/substitution.art/htdocs/app/web/";
        locations."/" = {
          tryFiles = "$uri $uri/ /index.html";
        };
        extraConfig = ''
          charset utf-8;
          client_max_body_size 200M;
        '';
      };

      # substitution.art / www.substitution.art
      "substitution.art" = {
        serverAliases = [ "www.substitution.art" ];
        forceSSL = true;
        sslCertificate = "/var/lib/secrets/ssl/substitution.art/fullchain.pem";
        sslCertificateKey = "/var/lib/secrets/ssl/substitution.art/key.pem";
        root = "/usr/share/webapps/substitution.art/htdocs/www/";
        extraConfig = ''
          charset utf-8;
          client_max_body_size 200M;
        '';
      };

      # bau.minnecker.com
      "bau.minnecker.com" = {
        forceSSL = true;
        sslCertificate = "/var/lib/secrets/ssl/minnecker.com/fullchain.pem";
        sslCertificateKey = "/var/lib/secrets/ssl/minnecker.com/key.pem";
        root = "/usr/share/webapps/bau.minnecker.com/Hausbau-MinneckerWebsite";
        globalRedirect = null;
        extraConfig = ''
          charset utf-8;
          client_max_body_size 10M;
          expires 1m;
          index home.html index.html;

          add_header Referrer-Policy "no-referrer" always;
          add_header X-Content-Type-Options "nosniff" always;
          add_header X-Frame-Options "SAMEORIGIN" always;
          add_header X-Permitted-Cross-Domain-Policies "none" always;
          add_header X-XSS-Protection "1; mode=block" always;

          # gzip settings matching original configuration
          gzip on;
          gzip_vary on;
          gzip_comp_level 9;
          gzip_min_length 256;
          gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
          gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;
        '';
      };

      # git.minnecker.com / git.flos.dev (Forgejo Proxy)
      "git.minnecker.com" = {
        forceSSL = true;
        sslCertificate = "/var/lib/secrets/ssl/minnecker.com/fullchain.pem";
        sslCertificateKey = "/var/lib/secrets/ssl/minnecker.com/key.pem";
        locations."/" = {
          proxyPass = "http://forgejo";
          proxyWebsockets = true;
          extraConfig = ''
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
          '';
        };
        extraConfig = ''
          charset utf-8;
          client_max_body_size 4G;
        '';
      };

      # idm.minnecker.com (Kanidm SSO & Web UI)
      "idm.minnecker.com" = {
        forceSSL = true;
        sslCertificate = "/var/lib/secrets/ssl/minnecker.com/fullchain.pem";
        sslCertificateKey = "/var/lib/secrets/ssl/minnecker.com/key.pem";
        locations."/" = {
          proxyPass = "https://idm";
          proxyWebsockets = true;
          extraConfig = ''
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_ssl_verify off;
          '';
        };
      };

      # monitoring.minnecker.com (Grafana Dashboard)
      "monitoring.minnecker.com" = {
        forceSSL = true;
        sslCertificate = "/var/lib/secrets/ssl/minnecker.com/fullchain.pem";
        sslCertificateKey = "/var/lib/secrets/ssl/minnecker.com/key.pem";
        locations."/" = {
          proxyPass = "http://nixmonitoring";
          proxyWebsockets = true;
          extraConfig = ''
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
          '';
        };
      };

      # ai.minnecker.com (Open WebUI LLM Interface)
      "ai.minnecker.com" = {
        forceSSL = true;
        sslCertificate = "/var/lib/secrets/ssl/minnecker.com/fullchain.pem";
        sslCertificateKey = "/var/lib/secrets/ssl/minnecker.com/key.pem";
        locations."/" = {
          proxyPass = "http://openwebui";
          proxyWebsockets = true;
          extraConfig = ''
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
          '';
        };
      };

      # ki.minnecker.com (LDAP Protected Proxy)
      "ki.minnecker.com" = {
        forceSSL = true;
        sslCertificate = "/var/lib/secrets/ssl/minnecker.com/fullchain.pem";
        sslCertificateKey = "/var/lib/secrets/ssl/minnecker.com/key.pem";
        locations."/" = {
          proxyPass = "http://ki";
          proxyWebsockets = true;
          extraConfig = ''
            auth_ldap "Forbidden";
            auth_ldap_servers mail_users;
            auth_delay 1s;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect off;
            proxy_buffering off;
            chunked_transfer_encoding off;
            proxy_set_header authorization "";
            proxy_set_header Authorization "";
          '';
        };
        extraConfig = ''
          charset utf-8;
          client_max_body_size 5M;
        '';
      };

      # kie.minnecker.com (Token-Gated OpenAI LLM Proxy)
      #
      # Public, bearer-token-gated reverse proxy to the OpenAI-compatible LLM
      # endpoint (192.168.1.196:52415, same backend Open WebUI uses). Clients
      # authenticate with `Authorization: Bearer <token>`; the token is checked
      # via a map directive ($kie_token_ok) generated at runtime from
      # /var/lib/kie-proxy/token. The client's Authorization header is then
      # OVERWRITTEN with the upstream's fixed key ("Bearer x") before proxying,
      # so the proxy token is never forwarded to the LLM backend.
      "kie.minnecker.com" = {
        forceSSL = true;
        sslCertificate = "/var/lib/secrets/ssl/minnecker.com/fullchain.pem";
        sslCertificateKey = "/var/lib/secrets/ssl/minnecker.com/key.pem";
        extraConfig = ''
          charset utf-8;
          client_max_body_size 100M;
        '';
        locations."/" = {
          proxyPass = "http://kiellm";
          proxyWebsockets = true;
          extraConfig = ''
            if ($kie_token_ok = 0) {
              return 401;
            }

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            # Replace the client's bearer token with the upstream LLM's fixed
            # key — the proxy gate token must not reach the backend.
            proxy_set_header Authorization "Bearer x";
            proxy_buffering off;
            chunked_transfer_encoding off;
            proxy_read_timeout 600;
            proxy_send_timeout 600;
          '';
        };
      };

      # localhost (Nginx Javascript Mail Auth Helper)
      "localhost" = {
        listen = [
          { addr = "127.0.0.1"; port = 80; }
          { addr = "[::1]"; port = 80; }
          { addr = "10.0.30.1"; port = 80; }
        ];
        extraConfig = ''
          js_import auth from ${./auth.js};
          error_log /var/log/nginx/localhost.err.log;
        '';
        locations."/hello" = {
          extraConfig = "js_content auth.hello;";
        };
        locations."/test/" = {
          extraConfig = "js_content auth.test;";
        };
        locations."/dbg_headers/" = {
          extraConfig = "js_content auth.printHeaders;";
        };
        locations."/auth/" = {
          extraConfig = "js_content auth.validate;";
        };
        locations."/ldapauth" = {
          proxyPass = "http://localhost/doldapauth";
          extraConfig = ''
            proxy_set_header Authorization "Basic $arg_auth";
            proxy_pass_header Authorization;
          '';
        };
        locations."/doldapauth" = {
          extraConfig = ''
            auth_ldap "Forbidden";
            auth_ldap_servers mail_users;
            auth_delay 10s;
            js_content auth.granted;
          '';
        };
      };

      # mail.minnecker.com (Roundcube)
      "mail.minnecker.com" = {
        forceSSL = true;
        sslCertificate = "/var/lib/secrets/ssl/minnecker.com/fullchain.pem";
        sslCertificateKey = "/var/lib/secrets/ssl/minnecker.com/key.pem";
        # Points to Roundcube files within Nix store
        root = "${config.services.roundcube.package}/public_html";
        locations."/" = {
          index = "index.php";
          extraConfig = "try_files $uri $uri/ /index.php?$args;";
        };
        locations."~ \\.php(/.*)?$" = {
          extraConfig = ''
            fastcgi_pass unix:${config.services.phpfpm.pools.roundcube.socket};
            fastcgi_index index.php;
            include ${config.services.nginx.package}/conf/fastcgi.conf;

            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            fastcgi_param SCRIPT_FILENAME $request_filename;
            fastcgi_param PATH_INFO $fastcgi_path_info;
          '';
        };
        extraConfig = ''
          charset utf-8;
          client_max_body_size 4G;
          fastcgi_hide_header X-Powered-By;
          fastcgi_hide_header X-Frame-Options;
          add_header Content-Security-Policy "default-src *  data: blob: 'unsafe-inline' 'unsafe-eval';script-src * data: blob: 'unsafe-inline' 'unsafe-eval';connect-src * data: blob: 'unsafe-inline';img-src * data: blob: 'unsafe-inline';frame-src * data: blob: ;style-src * data: blob: 'unsafe-inline';font-src * data: blob: 'unsafe-inline';worker-src *;";
        '';
      };

      # matrix.minnecker.com (Element Web client & Matrix Synapse Reverse Proxy)
      "matrix.minnecker.com" = {
        forceSSL = true;
        sslCertificate = "/var/lib/secrets/ssl/minnecker.com/fullchain.pem";
        sslCertificateKey = "/var/lib/secrets/ssl/minnecker.com/key.pem";
        root = "/usr/share/webapps/element/";
        extraConfig = ''
          charset utf-8;
          client_max_body_size 2G;
        '';
        locations."/.well-known/matrix/server" = {
          extraConfig = "return 200 '{ \"m.server\": \"matrix.minnecker.com:443\" }';";
        };
        locations."/.well-known/matrix/client" = {
          extraConfig = ''
            return 200 '{ "m.homeserver": { "base_url": "https://matrix.minnecker.com" } }';
          '';
        };
        locations."/_matrix" = {
          proxyPass = "http://matrix";
          extraConfig = ''
            proxy_http_version 1.1;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_read_timeout 600;
            proxy_send_timeout 600;
          '';
        };
      };

      # vault.minnecker.com (Vaultwarden Proxy)
      "vault.minnecker.com" = {
        forceSSL = true;
        sslCertificate = "/var/lib/secrets/ssl/minnecker.com/fullchain.pem";
        sslCertificateKey = "/var/lib/secrets/ssl/minnecker.com/key.pem";
        locations."/" = {
          proxyPass = "http://vaultwarden";
          extraConfig = ''
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $http_connection;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_buffering off;
            chunked_transfer_encoding off;
            add_header Access-Control-Allow-Credentials true;
            add_header Referrer-Policy "same-origin";
            error_log /var/log/nginx/vaultwarden.error.log;
          '';
        };
        extraConfig = ''
          # LAN + WireGuard clients (10.100.0.0/24 tunnel subnet,
          # 10.10.10.5 nixwireguard host address).
          allow 192.168.1.1/16;
          allow 10.100.0.0/24;
          allow 10.10.10.5;
          deny all;
          charset utf-8;
          # Bitwarden's default max attachment/send size is 625 MB.
          client_max_body_size 625M;
        '';
      };

      # wiki.minnecker.com (Wiki.js Proxy)
      "wiki.minnecker.com" = {
        forceSSL = true;
        sslCertificate = "/var/lib/secrets/ssl/minnecker.com/fullchain.pem";
        sslCertificateKey = "/var/lib/secrets/ssl/minnecker.com/key.pem";
        locations."/" = {
          proxyPass = "http://wikijs";
          extraConfig = ''
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_buffering off;
            error_log /var/log/nginx/wiki.error.log;
          '';
        };
        extraConfig = ''
          charset utf-8;
          client_max_body_size 500M;
        '';
      };

      # meet.minnecker.com (Jitsi Meet Proxy)
      "meet.minnecker.com" = {
        forceSSL = true;
        sslCertificate = "/var/lib/secrets/ssl/minnecker.com/fullchain.pem";
        sslCertificateKey = "/var/lib/secrets/ssl/minnecker.com/key.pem";
        locations."/" = {
          proxyPass = "http://jitsy";
          extraConfig = ''
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
          '';
        };
        extraConfig = ''
          charset utf-8;
          client_max_body_size 500M;
        '';
      };

      # www.minnecker.com / minnecker.com
      "www.minnecker.com" = {
        serverAliases = [ "minnecker.com" ];
        forceSSL = true;
        sslCertificate = "/var/lib/secrets/ssl/minnecker.com/fullchain.pem";
        sslCertificateKey = "/var/lib/secrets/ssl/minnecker.com/key.pem";
        root = "/usr/share/webapps/www.minnecker.com";
        locations."/api/whatsapp/webhook" = {
          proxyPass = "http://192.168.1.196:8002";
          extraConfig = ''
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_max_temp_file_size 0;
            client_max_body_size 10m;
            proxy_buffering off;
          '';
        };
        extraConfig = ''
          charset utf-8;
          client_max_body_size 100M;
          expires 1m;
          index home.html index.html;

          add_header Referrer-Policy "no-referrer" always;
          add_header X-Content-Type-Options "nosniff" always;
          add_header X-Frame-Options "SAMEORIGIN" always;
          add_header X-Permitted-Cross-Domain-Policies "none" always;
          add_header X-XSS-Protection "1; mode=block" always;

          # gzip settings matching original configuration
          gzip on;
          gzip_vary on;
          gzip_comp_level 9;
          gzip_min_length 256;
          gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
          gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;
        '';
      };
    };

    # Mail proxy removed: clients now connect directly to nixmail (Dovecot/
    # Postfix) via host-level port forwarding. The nginx mail proxy could not
    # pass XOAUTH2 through to Dovecot (it converts all auth to IMAP LOGIN /
    # SMTP AUTH PLAIN when re-authenticating to the backend), which blocked
    # OAuth2-based mail authentication. Dovecot and Postfix now handle TLS
    # and all auth mechanisms (XOAUTH2 + PLAIN) directly.
  };

  # 4. Roundcube Webmail Service Configuration
  services.roundcube = {
    enable = true;
    hostName = "mail.minnecker.com";
    configureNginx = false;
    
    # We do not run a local database, it resides on nixpostgres
    database = {
      host = "nixpostgres";
      passwordFile = "/var/lib/roundcube/pgpass";
    };

    # Inject variables dynamically at runtime from external secrets file (not in nix store)
    extraConfig = ''
      // Load database credentials from the shared Postgres secrets mount
      $db_password = rtrim(file_get_contents('/var/lib/secrets/postgres/roundcube/db-password'));
      $config['db_dsnw'] = "pgsql://roundcube:$db_password@nixpostgres/roundcube";

      // Load session encryption key from mounted secrets
      $des_key = rtrim(file_get_contents('/var/lib/secrets/nginx/roundcube-des-key.txt'));
      $config['des_key'] = $des_key;

      $config['imap_host'] = 'nixmail:143';
      $config['smtp_host'] = 'nixmail:587';
      $config['auto_create_user'] = true;
      $config['product_name'] = 'Mail';
      $config['language'] = 'de_DE';
      $config['prefer_html'] = false;
      $config['draft_autosave'] = 60;
      $config['mime_param_folding'] = 0;
      $config['max_message_size'] = "2G";

      // OAuth2 / OIDC login via Kanidm. Roundcube 1.6+ has built-in
      // OAuth2 support (no plugin): users click "Login with Kanidm",
      // authenticate in the browser (with MFA), and Roundcube receives an
      // access token it then uses to bind to Dovecot via XOAUTH2 — so
      // webmail needs no POSIX password.
      //
      // Uses the SAME 'mail' OAuth2 client as desktop/mobile mail apps
      // (public, PKCE, no client_secret). Kanidm's userinfo endpoint is
      // per-client, so all tokens Dovecot validates must come from the same
      // client. Dovecot's oauth2 passdb points at /oauth2/openid/mail/userinfo.
      $config['oauth_provider']      = 'generic';
      $config['oauth_provider_name'] = 'Kanidm';
      $config['oauth_client_id']     = 'mail';
      $config['oauth_client_secret'] = 'none';
      // OIDC discovery — Kanidm serves a per-client .well-known document
      // that supplies auth/token/userinfo/jwks endpoints.
      $config['oauth_config_uri']    = 'https://idm.minnecker.com/oauth2/openid/mail/.well-known/openid-configuration';
      $config['oauth_scope']         = 'openid email profile';
      // Resolve the IMAP username from the userinfo `email` claim — must
      // match Dovecot's oauth2 username_attribute (also `email`).
      $config['oauth_identity_fields'] = ['email'];
      // Send users straight to Kanidm SSO on the login page.
      $config['oauth_login_redirect'] = true;
      // Explicit XOAUTH2 — Dovecot advertises this mechanism; don't rely on
      // Roundcube's auto-selection ('OAUTH' default may pick OAUTHBEARER
      // which Dovecot also supports but the format can differ).
      $config['oauth_auth_type'] = 'XOAUTH2';
      // Cache discovery/JWKS in the Roundcube DB (avoids re-fetching on
      // every login; required/recommended when oauth_config_uri is set).
      $config['oauth_cache']     = 'db';
      $config['oauth_cache_ttl'] = 600;
    '';

    # Plugins used in original Roundcube installation
    plugins = [
      "additional_message_headers"
      "attachment_reminder"
      "enigma"
      "identity_select"
      "managesieve"
      "newmail_notifier"
      "show_additional_headers"
    ];
  };

  # 5. Nextcloud Service Configuration
  services.nextcloud = {
    enable = true;
    hostName = "cloud.minnecker.com";
    package = pkgs.nextcloud33;

    datadir = "/var/lib/nextcloud-data";

    maxUploadSize = "6G";
    
    # We do not run a local database, it resides on nixpostgres
    database.createLocally = false;

    config = {
      dbtype = "pgsql";
      dbhost = "nixpostgres";
      dbname = "nextcloud";
      dbuser = "nextcloud";
      dbpassFile = "/var/lib/secrets/postgres/nextcloud/db-password";
      adminpassFile = "/var/lib/secrets/nginx/nextcloud-admin-password.txt";
      adminuser = "admin";
    };

    settings = {
      # Declare the local proxy as trusted, and crucially set
      # forwarded_for_headers to an EMPTY array. Nextcloud otherwise defaults
      # to reading HTTP_X_FORWARDED_FOR from trusted proxies; since this edge
      # does not append its own X-Forwarded-For, that default would let
      # clients spoof the IP Nextcloud sees (ban evasion) or collapse many
      # clients onto one value — the false "too many failed attempts" lockouts
      # Nextcloud suffered in the past. With an empty array, brute-force
      # protection and the audit log key solely off REMOTE_ADDR.
      trusted_proxies = [ "127.0.0.1" "::1" ];
      forwarded_for_headers = [];

      # idm.minnecker.com resolves to this host's own IP (10.20.20.14) via
      # networking.extraHosts, to dodge the hairpin-NAT self-reference
      # described in configuration.nix. Nextcloud's Guzzle HTTP client
      # (used by user_oidc to fetch the OIDC discovery/JWKS documents)
      # treats any RFC1918 destination as a private address and blocks it
      # (OC\Http\Client\DnsPinMiddleware → "violates local access rules"),
      # which surfaces at login as "Could not reach the provider". This
      # flag explicitly permits local-remote calls so the OIDC flow can
      # reach the IdP through the local nginx listener.
      allow_local_remote_servers = true;
    };
    
    configureRedis = true;

    # Install the OIDC client application
    extraAppsEnable = true;
    extraApps = {
      inherit (pkgs.nextcloud33Packages.apps) user_oidc;
    };
  };

  # The default nextcloud-setup runs "occ app:enable" which fails because
  # the Nextcloud webroot lives in the read-only Nix store. Override with a
  # minimal setup that skips app:enable — user_oidc is already installed via
  # extraApps and is enabled by nextcloud-setup-oidc on first boot.
  #
  # We explicitly LoadCredential the same secrets so credential-passing works
  # exactly like the module-generated unit.
  systemd.services.nextcloud-setup.unitConfig = { };
  systemd.services.nextcloud-setup = {
    # Re-add LoadCredential so secrets are available (module adds these but we
    # are overriding ExecStart which resets the whole unit).
    serviceConfig.LoadCredential = [
      "dbpass:${config.services.nextcloud.config.dbpassFile}"
      "adminpass:${config.services.nextcloud.config.adminpassFile}"
    ];
    serviceConfig.ExecStart = pkgs.writeShellScript "nextcloud-setup-override" ''
      source /etc/setup-variables
      set -euo pipefail

      export OCC_BIN="${config.services.nextcloud.occ}/bin/nextcloud-occ"
      CRED_DIR="$CREDENTIALS_DIRECTORY"

      if [ -z "$(<"$CRED_DIR/dbpass")" ]; then
        echo "dbpass is empty!" >&2; exit 1
      fi
      if [ -z "$(<"$CRED_DIR/adminpass")" ]; then
        echo "adminpass is empty!" >&2; exit 1
      fi

      if [[ ! -O "/var/lib/nextcloud-data/config" ]]; then
        echo "/var/lib/nextcloud-data/config not owned by nextcloud!" >&2; exit 1
      fi

      if [[ ! -s /var/lib/nextcloud-data/config/config.php ]]; then
        DBPASS="$(<"$CRED_DIR/dbpass")"
        ADMINPASS="$(<"$CRED_DIR/adminpass")"
        $OCC_BIN maintenance:install \
          --admin-pass "$ADMINPASS" \
          --admin-user "admin" \
          --data-dir "/var/lib/nextcloud-data/data" \
          --database "pgsql" \
          --database-host "nixpostgres" \
          --database-name "nextcloud" \
          --database-pass "$DBPASS" \
          --database-user "nextcloud"
      fi

      $OCC_BIN upgrade || true
      $OCC_BIN config:system:delete trusted_domains 2>/dev/null || true
      $OCC_BIN config:system:set trusted_domains 0 --value="cloud.minnecker.com"
      echo "Done."
    '';
  };

  # Auto-configure Nextcloud OIDC client registration on service start.
  #
  # Registration fetches the OIDC discovery document from idm.minnecker.com,
  # which is only reachable once networking + DNS are fully up. The service is
  # therefore allowed to retry: a failed registration exits non-zero and
  # systemd restarts it (Restart=on-failure) until it succeeds, at which
  # point the idempotency guard skips re-registration on later boots.
  systemd.services.nextcloud-setup-oidc = {
    description = "Configure Nextcloud OIDC Provider";
    after = [ "network-online.target" "nextcloud-setup.service" ];
    wants = [ "network-online.target" ];
    wantedBy = [ "multi-user.target" ];

    # curl is used to probe the IdP discovery endpoint before registration.
    path = [ pkgs.curl ];

    startLimitBurst = 10;
    startLimitIntervalSec = 300;

    serviceConfig = {
      Type = "oneshot";
      User = "root";
      Group = "root";
      Restart = "on-failure";
      RestartSec = 10;
    };

    serviceConfig.ExecStart = pkgs.writeShellScript "nextcloud-setup-oidc" ''
      set -euo pipefail
      occ="${config.services.nextcloud.occ}/bin/nextcloud-occ"
      discovery="https://idm.minnecker.com/oauth2/openid/nextcloud/.well-known/openid-configuration"

      # Ensure user_oidc app is enabled
      if ! $occ app:list | grep -q "user_oidc"; then
        $occ app:enable user_oidc
      fi

      # Make OIDC the default login method: hides the local login form and
      # auto-redirects to the IdP. Admins can still reach the native form via
      # https://cloud.minnecker.com/login?direct=1 as an escape hatch.
      $occ config:app:set --value=0 user_oidc allow_multiple_user_backends

      # Idempotency guard: nothing to do if the provider already exists.
      # (user_oidc:provider with no args lists all configured providers.)
      if $occ user_oidc:provider | grep -q "kanidm"; then
        echo "Kanidm OIDC provider already registered; nothing to do."
        exit 0
      fi

      if [ ! -f /var/lib/secrets/oauth2/nextcloud/secret ]; then
        echo "Error: /var/lib/secrets/oauth2/nextcloud/secret not found. Retrying."
        exit 1
      fi

      # Fail (and thus trigger a restart) if the IdP discovery endpoint is
      # not yet reachable — e.g. during early boot before DNS/networking settle.
      if ! curl -fsS --max-time 10 "$discovery" >/dev/null; then
        echo "Error: IdM discovery endpoint unreachable at $discovery. Retrying."
        exit 1
      fi

      client_secret=$(cat /var/lib/secrets/oauth2/nextcloud/secret)
      # user_oidc's occ command is `user_oidc:provider <identifier>` with
      # --clientid / --clientsecret / --discoveryuri options (not provider-add).
      $occ user_oidc:provider kanidm \
        --clientid="nextcloud" \
        --clientsecret="$client_secret" \
        --discoveryuri="$discovery" \
        --group-provisioning=1
      echo "Kanidm OIDC provider registered successfully."
    '';
  };

  # Auto-provision the bearer token for the kie.minnecker.com LLM proxy gate.
  #
  # /var/lib/secrets/nginx is a read-only bind mount on this container, so the
  # token lives in a writable state dir (/var/lib/kie-proxy). Generated once
  # with openssl on first boot and persisted across restarts. The oneshot also
  # (re)generates an nginx map snippet (nginx-map.conf) that maps the
  # client's Authorization header to $kie_token_ok (1 = match, 0 = deny);
  # this is included from commonHttpConfig. Both files are root:root 0600
  # since the nginx master (root) reads them at config parse time. Coupled
  # to nginx.service (partOf + bindsTo) so it re-runs on every (re)start.
  systemd.services.kie-proxy-token = {
    description = "Provision kie.minnecker.com proxy token + nginx map snippet";
    wantedBy = [ "nginx.service" ];
    before = [ "nginx.service" ];
    partOf = [ "nginx.service" ];
    bindsTo = [ "nginx.service" ];
    serviceConfig.Type = "oneshot";
    path = [ pkgs.openssl pkgs.coreutils ];
    script = ''
      set -euo pipefail
      d=/var/lib/kie-proxy
      install -d -m 750 -o root -g nginx "$d"
      f="$d/token"
      mapf="$d/nginx-map.conf"

      if [ ! -s "$f" ]; then
        echo "Generating new kie proxy token..."
        token=$(openssl rand -hex 32)
      else
        echo "kie proxy token already present — keeping it."
        token=$(cat "$f")
      fi

      # Write the token file (idempotent — never overwrite an existing one).
      # root:nginx 640 so the nginx master can read it but no other user.
      ( umask 027
        printf '%s\n' "$token" > "$f"
      )
      chmod 640 "$f"
      chown root:nginx "$f"

      # Always (re)generate the map snippet from the current token so it
      # stays in sync if the token file was manually rotated. root:nginx 640
      # so the nginx master (and pre-start config test) can read it.
      cat > "$mapf" <<EOF
      map \$http_authorization \$kie_token_ok {
          default 0;
          "Bearer $token" 1;
      }
      EOF
      chmod 640 "$mapf"
      chown root:nginx "$mapf"
    '';
  };

  # Auto-generate the .pgpass file for Roundcube in its writeable StateDirectory
  # to bypass permission issues with the read-only mounted secrets directory.
  systemd.services.roundcube-setup = {
    preStart = ''
      if [ -f /var/lib/secrets/postgres/roundcube/db-password ]; then
        password=$(cat /var/lib/secrets/postgres/roundcube/db-password)
        echo "*:*:*:roundcube:$password" > /var/lib/roundcube/pgpass
        chmod 600 /var/lib/roundcube/pgpass
      else
        echo "Error: /var/lib/secrets/postgres/roundcube/db-password not found!"
        exit 1
      fi
    '';
  };
}
